# Generated by Django 6.0.4 on 2026-04-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='notes',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='phone',
            new_name='phone_no',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='city',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='notes',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='phone',
            new_name='phone_no',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='village',
            new_name='place',
        ),
        migrations.AddField(
            model_name='buyer',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='buyer',
            name='gst_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='buyer',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='seller',
            name='gst_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='seller',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
