# Generated by Django 6.0.4 on 2026-04-26 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_notes_buyer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.buyer'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.seller'),
        ),
    ]
