# Generated by Django 6.0.4 on 2026-04-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_shipment_buyer_alter_shipment_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('place', models.CharField(blank=True, max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
