# Generated by Django 6.0.4 on 2026-04-26 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_broker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_number', models.CharField(max_length=50)),
                ('confirmation_date', models.DateField()),
                ('supplier_place', models.CharField(blank=True, max_length=100)),
                ('buyer_place', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quality', models.CharField(blank=True, max_length=100)),
                ('count', models.CharField(blank=True, max_length=50)),
                ('moisture', models.CharField(blank=True, max_length=50)),
                ('gunny', models.CharField(blank=True, max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('packing', models.CharField(blank=True, max_length=100)),
                ('delivery_at', models.CharField(blank=True, max_length=100)),
                ('date_of_delivery', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.buyer')),
                ('buyer_broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_confirmations', to='transactions.broker')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.seller')),
                ('supplier_broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_confirmations', to='transactions.broker')),
            ],
        ),
    ]
