# Generated by Django 6.0.4 on 2026-04-27 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50)),
                ('bill_date', models.DateField()),
                ('number_of_bags', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lorry_advance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lorry_number', models.CharField(blank=True, max_length=50)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('others', models.TextField(blank=True)),
                ('confirmation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.confirmation')),
            ],
        ),
    ]
