# Generated by Django 6.0.4 on 2026-04-27 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='confirmation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='transactions.confirmation'),
        ),
    ]
