# Generated by Django 6.0.4 on 2026-04-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_bill_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='confirmation_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
