# Generated by Django 6.0.4 on 2026-04-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_confirmation_confirmation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='packing_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
