# Generated by Django 6.0.4 on 2026-05-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_payment_paymentline'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
