# Generated by Django 6.0.4 on 2026-05-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_buyer_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
