# Generated by Django 6.0.4 on 2026-05-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_broker_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='buyer_commission_rate',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='supplier_commission_rate',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
    ]
